### ISSUE TITLE
Need better end-of run procedure in DWC producer.

### ISSUE THREAD

**Issue by andreypz** [HGCDAQ/eudaq#72]
I think that DWC producer may still be the cause of crashes at the end of runs.
Here is how one could try to resolve this:
* Put [EORE](https://github.com/HGCDAQ/eudaq/blob/358fb7cef28e30281ccc77af96a2250f3e89beaf/producers/cmshgcal_dwc/src/WireChamberProducer.cxx#L185) at the end of OnStopRun() method.

If that does not help can try this:
1. Introduce a new variable *processed_event*. Then [here](https://github.com/HGCDAQ/eudaq/blob/358fb7cef28e30281ccc77af96a2250f3e89beaf/producers/cmshgcal_dwc/src/WireChamberProducer.cxx#L182) put something like this:
` while (!processed_event)  eudaq::mSleep(200);`
2. At the beginning of [this loop](https://github.com/HGCDAQ/eudaq/blob/358fb7cef28e30281ccc77af96a2250f3e89beaf/producers/cmshgcal_dwc/src/WireChamberProducer.cxx#L234-L293) put `processed_event=false`. And at the end `processed_event=true`

I'm away from CERN this week, so I'm not going to do that. I hope @ThorbenQuast or @asteencern could test these options.

**Comment by ThorbenQuast** [comment]
Both suggestions are added to the DWC producer now. Effect to be assessed when data taking continues.
